module.exports = {
  content: [
    './index.html',
    './src/**/*.vue',
    './src/**/*.js',
    './public/assets/js/main.js',
  ],
  css: ['./public/assets/vendor/bootstrap/css/bootstrap.min.css'],
  output: './public/assets/vendor/bootstrap/css/',
  safelist: [
    'active',
    'show',
    'hide',
    'collapsing',
    'collapse',
    'dropdown',
    'dropdown-menu',
    'dropdown-item',
    'modal',
    'offcanvas',
    'carousel',
    'fade',
    'tab-pane',
    'nav-link',
    'nav-item',
    'btn',
    'btn-close',
    'tooltip',
    'popover',
    'toast',
  ],
};
